name: CI
on: [push, pull_request]

jobs:
  test:
    name: Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      run: |
        curl https://sh.rustup.rs | sh -s -- -y
        echo "##[add-path]$HOME/.cargo/bin"
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
    - run: wasm-pack build


  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
	node-version: 12
	registry-url: https://registry.npmjs.org/
    - run: cd loader && npm publish
      env:
	NODE_AUTH_TOKEN: ${{secrets.npm_token}}
