name: CI
on: [push, pull_request]

jobs:
  build:
    name: Build wasm-interface-types
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    # - name: Install Rust
    #   run: |
    #     curl https://sh.rustup.rs | sh -s -- -y
    #     echo "##[add-path]$HOME/.cargo/bin"
    # - name: Install wasm-pack
    #   run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    # - run: wasm-pack build
    # - run: npm publish
    #   if: startsWith(github.ref, 'refs/tags/')
    #   working-directory: pkg
    #   env:
    #     NODE_AUTH_TOKEN: ${{secrets.npm_token}}
    - run: npm pack
      working-directory: loader
    - run: |
        set -ex
        npm install -g github-release-cli
        github-release delete \
          --token ${{ secrets.npm_token }} \
          --owner ${{ github.event.repository.owner.name }} \
          --repo ${{ github.event.repository.name }} \
          --tag "dev"
        github-release upload \
          --token ${{ secrets.npm_token }} \
          --owner ${{ github.event.repository.owner.name }} \
          --repo ${{ github.event.repository.name }} \
          --tag "dev" \
          --name "Latest CI Build" \
          --body "Automatic publish from CI" \
          loader/*.tgz
      if: github.ref == 'refs/heads/master'
      name: Publish master to github dev release


  # loader:
  #   name: Build wasm-interface-types-loader
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v1
  #   - uses: actions/setup-node@v1
  #     with:
  #       node-version: 12
  #       registry-url: https://registry.npmjs.org/
  #   - run: npm publish
  #     if: startsWith(github.ref, 'refs/tags/')
  #     working-directory: loader
  #     env:
  #       NODE_AUTH_TOKEN: ${{secrets.npm_token}}
  #   - run: npm pack
  #     working-directory: loader
