name: CI
on: [push, pull_request]

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Rust (
      run: rustup update stable && rustup default stable
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
    - run: wasm-pack build

