name: CI
on:
  push:
    branches:
    - master
    tags:
    - '!dev'
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Build wasm-interface-types
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      run: |
        curl https://sh.rustup.rs | sh -s -- -y
        echo "##[add-path]$HOME/.cargo/bin"
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    - run: wasm-pack build

    # Publish to github releases on each commit to master
    - run: |
        (cd loader && npm pack)
        (cd pkg && npm pack)
        curl -X DELETE https://api.github.com/repos/${{ github.repository }}/git/refs/tags/dev?access_token=${{ secrets.github_token }}
        npm install -g github-release-cli
        github-release delete \
          --token ${{ secrets.github_token }} \
          --owner ${{ github.event.repository.owner.name }} \
          --repo ${{ github.event.repository.name }} \
          --tag "dev"
        github-release upload \
          --token ${{ secrets.github_token }} \
          --owner ${{ github.event.repository.owner.name }} \
          --repo ${{ github.event.repository.name }} \
          --tag "dev" \
          --name "Latest CI Build" \
          --body "Automatic publish from CI" \
          --prerelease=true \
          pkg/*.tgz \
          loader/*.tgz
      if: github.ref == 'refs/heads/master'
      name: Publish master to github dev release

    # Publish to NPM  on tags
    - run: |
        (cd pkg && npm publish)
        (cd loader && npm publish)
      name: Publish to NPM
      if: startsWith(github.ref, 'refs/tags/')
      env:
        NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
