name: CI
on: [push, pull_request]

jobs:
  build:
    name: Build wasm-interface-types
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      run: |
        curl https://sh.rustup.rs | sh -s -- -y
        echo "##[add-path]$HOME/.cargo/bin"
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    - run: wasm-pack build
    - run: cd pkg && npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      if: startsWith(github.ref, 'refs/tags/')


  loader:
    name: Build wasm-interface-types-loader
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    - run: cd loader && npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      if: startsWith(github.ref, 'refs/tags/')
