name: CI
on: [push, pull_request]

jobs:
  test:
    name: Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      run: |
        curl https://sh.rustup.rs | sh -s -- -y
        echo "##[add-path]$HOME/.cargo/bin"
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
    - run: wasm-pack build

